(HOMEWORK_MODULE, HOMEWORK_TOPIC, HOMEWORK_MENTOR, HOMEWORK_MESSAGE, HOMEWORK_SELECT_TYPE,
 HOMEWORK_WAITING, PAYMENT_WAITING, PAYMENT_CONFIRMATION, BROADCAST_WAITING, WAITING_MENTOR_NAME, WAITING_MENTOR_TG_NEW,
 CALL_SCHEDULE, CALL_CONFIRMATION, CALL_SCHEDULE_DATE, CALL_SCHEDULE_TIME, WAITING_MENTOR_DIRECTION,WAITING_MENTOR_TG_REMOVE) = range(17)
